name: Compile Arduino Sketches

on:
  push:
    paths:
      - arduino/**/*.ino
  pull_request:
    paths:
      - arduino/**/*.ino

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.4.0

      - name: Compile sketch
        uses: arduino/compile-sketches@v1.0.1
        with:
          fqbn: "arduino:avr:mega"
          sketch-paths: |
            - arduino/blink
            - arduino/main
            - arduino/components
          libraries: |
            # BME680
            - source-url: https://github.com/adafruit/Adafruit_BusIO.git
            - source-url: https://github.com/adafruit/Adafruit_BME680.git
            - source-url: https://github.com/adafruit/Adafruit-GFX-Library.git
            - source-url: https://github.com/adafruit/Adafruit_SSD1306.git
            - source-url: https://github.com/adafruit/Adafruit_Sensor.git

            # clockModule
            - source-url: https://github.com/DFRobot/Gravity-I2C-SD2405-RTC-Module.git
              source-path: GravityRtc

            # e-Paper
            # - source-url: https://github.com/adafruit/Adafruit_BusIO.git
            # - source-url: https://github.com/adafruit/Adafruit-GFX-Library.git
            - source-url: https://github.com/ZinggJM/GxEPD2.git

            # GPS
            - source-url: https://github.com/mikalhart/TinyGPSPlus.git

            # microSD
            - name: SD

            # temperatureOutside
            # - source-url: https://github.com/adafruit/Adafruit_BusIO.git
            - source-url: https://github.com/adafruit/Adafruit_AM2315.git
